Models/CompoundingModel.cs
using ETFCalculatorApp.Enums;

namespace ETFCalculatorApp.Models
{
    public class CompoundingModel
    {
        public double StartingAmount { get; set; }

        public double RecurringInvestmentAmount { get; set; }

        public int TotalInvestmentYears { get; set; }

        public double ExpectedGrowthPercentage { get; set; }

        public ECompoundingInterval RecurringInvestmentInterval { get; set; }

        public ECompoundingInterval CompoundingInterval { get; set; }

        public double TotalResult { get; set; }

        public int DeemedDisposal = (int)EDeemedDisposal.DeemedDisposalLength;


        public CompoundingModel() 
        {
            StartingAmount = 0;
            RecurringInvestmentAmount = 0;
            TotalInvestmentYears = 0;
            ExpectedGrowthPercentage = 0;
            TotalResult = 0;
            RecurringInvestmentInterval = ECompoundingInterval.Monthly;
            CompoundingInterval = ECompoundingInterval.Monthly;
        }
    }
}

Models/ErrorViewModel.cs
namespace ETFCalculatorApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/CalculatorController.cs
using ETFCalculatorApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ETFCalculatorApp.Controllers
{
    public class CalculatorController : Controller
    {
        private readonly ILogger<CalculatorController> _logger;

        public CalculatorController(ILogger<CalculatorController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            CompoundingModel m = new CompoundingModel();

            m.StartingAmount = 1000;
            m.RecurringInvestmentAmount = 500;
            m.ExpectedGrowthPercentage = 2; // 2%
            m.CompoundingInterval = Enums.ECompoundingInterval.Monthly;
            m.TotalInvestmentYears = 5;
            m.RecurringInvestmentInterval = Enums.ECompoundingInterval.Monthly;

            m.TotalResult = CalculateMainCompoundingEquation(m);
            return View(m);
        }

        public double CalculateMainCompoundingEquation(CompoundingModel m)
        {
            double principal = m.StartingAmount;
            double rate = m.ExpectedGrowthPercentage / 100;
            int time = m.TotalInvestmentYears * (int)m.CompoundingInterval;
            double interest = rate / (int)m.CompoundingInterval;
            double result = principal * Math.Pow((1 + interest), time);

            // If there's a recurring investment
            if (m.RecurringInvestmentAmount > 0)
            {
                double recurringInvestment = m.RecurringInvestmentAmount;
                int recurringTime = m.TotalInvestmentYears * (int)m.RecurringInvestmentInterval;
                for (int i = 0; i < recurringTime; i++)
                {
                    result += recurringInvestment * Math.Pow((1 + interest), (recurringTime - i));
                }
            }

            return result;
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Calculator/Index.cshtml
@model ETFCalculatorApp.Models.CompoundingModel;

@{
    ViewData["Title"] = "ETF Investments Calculator";
}

<div class="text-center" style="max-width:50%;">

    <h3>Editor:</h3>
    <table>
        <tr>
            <td class="inputlabel">@CommonStrings.StartingAmount</td>
            <td>@Html.EditorFor(x => x.StartingAmount)</td>
        </tr>
        <tr>
            <td class="inputlabel">@CommonStrings.RecurringInvestmentAmount</td>
            <td>@Html.EditorFor(x => x.RecurringInvestmentAmount)</td>
        </tr>
        <tr>
            <td class="inputlabel">@CommonStrings.TotalInvestmentYears</td>
            <td>@Html.EditorFor(x => x.TotalInvestmentYears)</td>
        </tr>
        <tr>
            <td class="inputlabel">@CommonStrings.ExpectedInterest @CommonStrings.PercentageSymbol</td>
            <td>@Html.EditorFor(x => x.ExpectedGrowthPercentage)</td>
        </tr>
        <tr>
            <td class="inputlabel">@CommonStrings.RecurringInvestmentInterval</td>
            <td>@Html.EditorFor(x => x.RecurringInvestmentInterval)</td>
        </tr>
        <tr>
            <td class="inputlabel">@CommonStrings.CompoundingInterval</td>
            <td>@Html.EditorFor(x => x.CompoundingInterval)</td>
        </tr>
        <tr>
            <td id="calculatebtn" class="btn" onclick="Calculate()">@CommonStrings.Calculate</td>

            <td id="resetbtn" class="btn" onclick="Reset()">@CommonStrings.Reset</td>
        </tr>
        <tr class="totalbox">
            <td class="inputlabel">@CommonStrings.Total</td>
            <td>@Model.TotalResult.ToString("F2")</td>
        </tr>
    </table>

</div>

<script>
    function Calculate()
    {
        // do maths in controller with stuff
    }
    
    function Reset()
    {
        // clear fields
    }

</script>

<style>

    .inputlabel{
        text-align:right;
    }

    tr{
        padding-bottom:10px;
    }

    td{
        padding-right:15px;
    }

    .totalbox{
        padding-top:20px;
    }
    
</style>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ETFCalculatorApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ETFCalculatorApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Calculator" asp-action="Index">ETFCalculatorApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Calculator" asp-action="Index">Calculator</a>
                        </li>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ETFCalculatorApp
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>